name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Dart/Flutter Package Analyzer
        uses: axel-op/dart-package-analyzer@v2
        with:
          # Token to connect to Github. Use secrets.GITHUB_TOKEN
          githubToken: ${{ secrets.TOKEN }}
